language: ruby
jdk: openjdk11
rvm: 2.5
before_install: gem install jekyll
before_script:
- wget -q https://fhir.github.io/latest-ig-publisher/org.hl7.fhir.validator.jar -O validator.jar
- wget -q http://hl7.org/fhir/uv/ips/2019Sep/validator.pack -O ips.pack
script:
- mkdir input-cache
- wget -q https://fhir.github.io/latest-ig-publisher/org.hl7.fhir.publisher.jar -O input-cache/org.hl7.fhir.publisher.jar
- JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
- java -jar input-cache/org.hl7.fhir.publisher.jar -ig ig.ini
- java -jar validator.jar -version 4.0.1 -ig ips.pack -ig output/validator-de.bbmri.fhir.pack input/examples
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: output
  on:
    branch: master
